routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* vista de idiomas  */
    Route::group(['middleware' => ['web']], function () {
  	    Route::resource('/','AdminController');

		Route::group(['middleware' => ['web']], function () {
			Route::get('lang/{lang}', function ($lang) {
			     App::setLocale($lang);
			        session(['lang' => $lang]);
				          return \Redirect::back();
			             })->where([
				                 'lang' => 'en|es|fr|pt'
         ]);
        });
       });
    /* fin de ruta de idiomas  */
Auth::routes();
Route::get('/respuesta',function(){
  return view('response');
});
Route::get('activacion/{code}','UserController@activate');
Route::post('complete/{id}','UserController@complete');
// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('cities/{id}','Auth\RegisterController@getCities');
Route::get('lada/{id}','Auth\RegisterController@getlada');

Route::get('reactivacion',function(){
  return view('auth.reactivacion');
});
  /* vista de validador de correo si existe */
  Route::post('validacorreor','UserController@validar');
  /* fin de ruta de validaro de correo */

Route::group(['middleware'=>'auth'],function(){
          Route::get('/home', 'HomeController@index')->name('home');
          Route::resource('micuestionarios','DapauditorController');
          //  Cuestionarios asignados al cliente
          Route::resource('miscuestionarios','MisCuestionariosController');
          Route::get('subsecciones/{id}','MisCuestionariosController@getSubsection')->name('subsecciones.inicio');
          Route::get('preguntas/{seccion}/{subseccion}','MisCuestionariosController@getQuestions')->name('preguntas.inicio');

          // Administrador de Cuestionarios
          Route::get('respuesta/respuesta/{val1}','AnswerController@respuesta');
          Route::resource('respuesta','AnswerController');
          Route::resource('pregunta','QuestionController');
          Route::resource('cuestionario','QuestionnaireController');
          Route::get('cuestionariostatus/{st}','QuestionnaireController@muestraActivInac');
          Route::resource('asingapregunta','QuestionnaireAnswerController');
          Route::get('tipocuest/{id}','QuestionnaireAnswerController@getCuestionarios');
          Route::resource('tipocuestionario','QuestionnaireTypeController');
          Route::resource('configcuestionario','QuestionnaireConfigurationController');
          Route::get('respuestaselect','AnswerController@getAnswer');
          Route::get('preguntaselect','QuestionController@getQuestion');
          Route::post('savetemplate','FilesController@guardaTemplate'); // Ruta para guardar los templates(Archivos) para cada respuesta
          Route::resource('file','FilesController');
          Route::resource('fileTemplate','FileTemplateController'); // Ruta que envia a la pestaña para cargar los templates por pregunta/respuesta(Archivos)
          Route::resource('tempcuest','FileTemplateCuestionarioController'); // Ruta que envia a la pestaña para cargar los templates por cuestionario(Archivos)
          Route::resource('filecuest','FilesQuestionarieController'); // Ruta que envia a la pestaña para cargar los templates por pregunta/respuesta(Archivos)
          Route::get('download/{file}','FilesController@download');
          Route::get('downloadCuest/{file}','FilesQuestionarieController@download');
          Route::get('downloadTemplate/{file}','FileTemplateController@download');
          Route::get('downloadTemplateCues/{file}','FilesQuestionarieController@download');
          Route::get('signiv1/{id}','FilesController@signiv1'); // Enviar al siguiente nivel os archivos al perfil auditor desde el perfil usuario
          Route::get('signiv1Cuest/{id}','FilesQuestionarieController@signiv1'); // Enviar al siguiente nivel os archivos al perfil auditor desde el perfil usuario
          Route::get('signiv1Temp/{id}','FileTemplateController@signiv1');

          Route::resource('catalogo','CatalogoController');
          // Administrador alta de tipo de giro
<<<<<<< HEAD
 
=======

>>>>>>> 8f4e320ea0510daec4932c459c7ba8e038e10003
          Route::resource('giro','GiroController');
          Route::resource('empresa','EmpresaController');
          Route::resource('planes','PlanesController');
          Route::resource('dap','DapController');
          Route::resource('pais','PaisController');
          Route::resource('ciudad','CiudadController');
          Route::resource('agrega','Contri_citiController');
          Route::resource('tipoArchivo','TipoArchivoController');
          Route::resource('calificacionArchivo','CalificacionArchivoController');


      Route::resource('user','UserController');

      Route::middleware('role:Admin')->put('user/{user}/roles','UsersRolesController@update')->name('user.roles.update');

      Route::middleware('role:Admin')->put('user/{user}/permissions','UsersPermissionsController@update')->name('user.permissions.update');

      Route::resource('roles','RoleController');

      Route::resource('permissions','PermissionsController');

      /* ruta para ver el email la vista */
      Route::get('email', function(){
        return new App\Mail\LoginCredentials(App\User::first(),'123456');
      });
      Route::resource('auditFile','AuditoriaArchivosController');
      Route::resource('analisis','AnalisController');
      Route::get('valor/{id}','AnalisController@Valorcatalogo');
      Route::get('grado/{id}','AnalisController@GradoRiesgo');
      Route::get('val/{id}','AriesgoController@Valorcatalogo');
      Route::get('grad/{id}','AriesgoController@GradoRiesgo');
      Route::resource('ariesgo','AriesgoController');
      Route::resource('ariesgoEjec','AriesgoEjecutivoController');
      Route::resource('operacion','catalog_masterController');
      Route::resource('actividad','ActividadController');
      Route::resource('descripcion','DescripcionController');
      Route::resource('catalogos','CataAnalisisController');

      Route::get('descargar-productos', 'GiroController@pdf')->name('products.pdf');
      Route::get('descargar-producto', 'GiroController@excel')->name('products.excel');
      // Route::get('pdf', 'PdfController@invoice');
      Route::get('analisis', 'AriesgoController@pdf')->name('alanisis.pdf');
      Route::get('analisisEjec', 'AriesgoEjecutivoController@pdf')->name('analisisEjec.pdf');
      Route::get('analisisEjecGr', 'AriesgoEjecutivoController@muestraContenido')->name('analisisEjecGr.muestraContenido'); // Ruta para guardar la imagen generada de la grfica
      Route::resource('divisas', 'DivisasController');
      Route::resource('cotizador', 'CotizadorController');
      Route::get('div/{id}','CotizadorController@getid');
      Route::resource('cotizaciones', 'CotizadorUser');
      Route::get('pdfcotizacion', 'CotizadorUser@pdf')->name('pdfcotizacion.pdf');
      Route::resource('admincotizador', 'AdminCotizadorController');

});

Route::resource('prueba','DapController');

resources/views/miscuestionarios/form/archivos.blade.php
{!! Form::open(['route'=> 'file.store', 'method' => 'POST', 'files'=>'true', 'id' => 'my-dropzone' , 'class' => 'dropzone']) !!}
  {{ csrf_field() }}
  <input type="hidden" id="id" name="id" />
  <div class="dz-message" >
      Carga tus archivos
  </div>
  <div class="dropzone-previews"></div>
  <button type="submit" class="btn btn-success" id="submit">Save</button>
{!! Form::close() !!}

resources/views/miscuestionarios/form/preguntas.blade.php
@extends('layouts.adm')
@section('content')
@include('miscuestionarios.modal.templateCuestionario')

  <div class="inner-wrapper">
      <section role="main" class="content-body pb-0">
          	<section role="main" class="content-body pb-0">
                	<div class="col-md-12 ">
                    <section class="card card-featured card-featured-primary mb-4">
                      <header class="card-header">
                        <div class="row">
                          <div class="col-lg-7">
                            <h2 class="card-title blanco">
                              <input type="hidden" id="token" name="token" value="{{ csrf_token() }}" content="{{ csrf_token() }}" />
                            </h2>
                          </div>
                          <div class="col-lg-2">
                          </div>
                          <div class="col-lg-1">
                            <input type="hidden" id="totPreguntas" name="totPreguntas" value="{{ count($arrPreguntasRespuestas) }}" />
                            <a type="button" class=" btn-outline btn-link" href="{{ URL::previous() }}"style="color:#fff;">	<i class="fa fa-mail-reply-all"> 	Regresar</i></a>
                          </div>
                          <div class="col-lg-1">
                            <button type="button" class=" btn-outline btn-link" style="color:#fff;"
                                data-toggle='modal' data-target='#descargaTemplatesUser'
                                id="descargaTemplatesUser">Templates</button>
                          </div>
                          <div class="col-lg-1">
                            <a type="" class="btn-outline btn-link" href="{{URL("miscuestionarios")}}" style="color:#fff;"> <i class="fa fa-plus"> Guardar</i></a>
                          </div>
                        </div>
                      </header>
                      <div class="row">
                        <div class="col-lg-12">
                          <div class="card-body">
                            <div class="col-lg-12 col-xl-12">
                              <div class="accordion accordion-primary " id="accordion2Primary">

                                <div class="card card-default">
                                  <div class="card-header">
                                    <h4 class="card-title m-0">
                                      <div class="row">
                                        <div class="col-md-12 col-lg-12 col-xl-12">
                                          <div class="row">
                                            <div class="col-md-6 col-lg-6 col-xl-6">
                                              <a href="#2" aria-expanded="true">
                                                {{$nombreSeccion[0]->nombreSeccion}}
                                              </a>
                                            </div>
                                            <div class="col-md-6 col-lg-6 col-xl-6">
                                              <a id="porcentaje" aria-expanded="true">
                                                Porcentaje: 0%
                                              </a>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </h4>
                                  </div>

                                  <div id="2">
                                    <div class="card-body">
                                      <h4 class=" letra2">{{$nombreSubseccion[0]->nombreSubseccion}}</h4>
                                      <table border="0" width="100%">
                                        <tbody>
                                          <?php $totalPreguntas = count($arrPreguntasRespuestas); ?>
                                          @foreach($arrPreguntasRespuestas as $pregunta => $valores)
                                            <tr>
                                               <td colspan="6">
                                                  <h4 class="letra3">{{$pregunta}}</h4>
                                                  <h4></h4>
                                               </td>
                                            </tr>
                                            <tr>
                                               <td colspan="">&nbsp;</td>
                                            </tr>
                                            <tr>
                                               @foreach($valores as $valor)
                                                <td align="center">{{$valor['texto']}}</td>
                                               @endforeach
                                            </tr>
                                            <tr>
                                               @foreach($valores as $valor)
                                                <td align="center" class="datos">
                                                  <?php
                                                    if($valor['tipoResp'] == "4"){
                                                      echo '<input type="radio" name="radio_12530" id="value_'.$valor["id"].'" onclick="guardaRespuestaRadioCS('.$valor["id"].','.$valor['valor'].','.$valor['idPregunta'].','.$valor['idCuestion'].', '.$valor['idSeccion'].','.($valor['noPregunta']+1).','.$valor['idSubseccion'].')" value="26303">';
                                                    }else if($valor['tipoResp'] == "3"){
                                                      echo '<select name="nivelCumplimiento" id="value" class="form-control col-lg-6" onChange="guardarRespuestaSelectCS('.$valor['id'].',this.value,'.$valor['idPregunta'].','.$valor['idCuestion'].','.$valor['idSeccion'].','.($valor['noPregunta']+1).','.$valor['idSubseccion'].')">
                                                            <option value="0">Seleccionar</option>
                                                            <option value="1">1</option>
                                                            <option value="2">2</option>
                                                            <option value="3">3</option>
                                                            <option value="4">4</option>
                                                            <option value="5">5</option>
                                                          </select>';
                                                    }else if($valor['tipoResp'] == "7"){
                                                      echo '<textarea id="value" name="value" style="height:40px;" autofocus="" onblur="guardarRespuestaTextareaCS('.$valor["id"].',this.value,'.$valor['idPregunta'].','.$valor['idCuestion'].', '.$valor['idSeccion'].','.($valor['noPregunta']+1).','.$valor['idSubseccion'].')" cols="15" class="form-control"></textarea>';
                                                    }else if($valor['tipoResp'] == "1"){
                                                      echo '<input type="text" id="value" name="value" class="form-control tama " col-md-2="" onblur="guardarRespuestaTextCS('.$valor["id"].',this.value,'.$valor['idPregunta'].','.$valor['idCuestion'].', '.$valor['idSeccion'].','.($valor['noPregunta']+1).','.$valor['idSubseccion'].')" value="">';
                                                    }else if($valor['tipoResp'] == "2"){
                                                      echo '<a href="'.route('file.index',['id'=>$valor['id'],'name'=>$valor['idCuestion'],'folio'=>$folio]).'" class="btn btn-primary" title="Editar"><i class="fa fa-edit"></i></a>';
                                                    }
                                                  ?>
                                                </td>
                                               @endforeach
                                            </tr>
                                          @endforeach
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>

                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </section>
                  </div>
            </section>
      </section>
  </div>
  <script>
  $(document).ready(function(e){

    var totalPreguntas = "<?php echo $totalPreguntas; ?>" ;

    $('.nivelCumplimiento').change(function(){
      var totalNivelCumplimiento = 0;
      var datoNivelCumplimiento = 0;
      $("select").each(function(){
        datoNivelCumplimiento = $(this).val();
        if($.isNumeric(datoNivelCumplimiento)){
            totalNivelCumplimiento += parseInt(datoNivelCumplimiento);
        }
      });
      var porcentaje = (totalNivelCumplimiento / totalPreguntas)
      $('#porcentaje').text('Porcentaje: '+porcentaje.toFixed(2)+'%');
    });

    $('#subeFilesM').on('show.bs.modal', function(e){
        var id = $(e.relatedTarget).data().id;
        $(e.currentTarget).find('#id').val(id);
    });

  });
  </script>
@stop

resources/views/miscuestionarios/form/sinsecciones.blade.php
@extends('layouts.adm')
@section('content')
<style media="screen">
.wrapper {
  display: grid;
  grid-template-columns: 100px repeat(3, 3fr) 100px;
}

.nueva {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
    border-color: red;
}
.tama{
  width: 90%;
}
</style>

@section('scripts')
    {!!Html::script('js/Generics.js')!!}
    {!!Html::script('js/admin/update_miscuestionarios.js')!!}
@endsection

<!-- Modal para cargar diferentes archivos -->
  <div class="inner-wrapper">
      <section role="main" class="content-body pb-0">
<<<<<<< HEAD
            <section role="main" class="content-body pb-0">
=======
          	<section role="main" class="content-body pb-0">
>>>>>>> 8f4e320ea0510daec4932c459c7ba8e038e10003
                    <section class="card card-featured card-featured-primary mb-4">
                      <header class="card-header">
                        <div class="row">
                          <div class="col-lg-7">
                            <h2 class="card-title blanco">
                                {{ $idCuestionario[0]->quname }}
                            </h2>
                          </div>
                          <div class="col-lg-2">
                          </div>
                          @can('Crear Cotizacion', new App\quotations)
                          <div class="col-lg-1">
                              <a type="" class="btn-outline btn-link"  style="color:#fff;" href="{{ route('cotizador.index',['id' => $folio,'id2'=>$id2,'empresa'=>$empresa,'idcues'=>$idcues])}}"> <i class="fa fa-plus"> Cotizar</i></a>
                          </div>
                          @endcan
                          <div class="col-lg-1">
<<<<<<< HEAD
                            <a type="" class=" btn-outline btn-link" href="{{ URL::previous() }}"style="color:#fff;">   <i class="fa fa-mail-reply-all">    Regresar</i></a>
=======
                            <a type="" class=" btn-outline btn-link" href="{{ URL::previous() }}"style="color:#fff;">	<i class="fa fa-mail-reply-all"> 	Regresar</i></a>
>>>>>>> 8f4e320ea0510daec4932c459c7ba8e038e10003
                          </div>
                          <div class="col-lg-1">
                            <a type="" class="btn-outline btn-link" href="{{URL("miscuestionarios")}}" style="color:#fff;"> <i class="fa fa-plus"> Guardar</i></a>
                          </div>
                        </div>
                      </header>
                      <div class="card-body">
                            <div class="contono">
                              <h4 class=" text-whrite letra"><!--Planeación de la seguridad--></h4>
                            </div>
                            <div class="form-group ">
                              <!--<h4 class=" letra2">1.1 - Análisis de riesgos</h4>-->
                                <div class=" conte">
                                  <input type="hidden" id="totPreguntas" name="totPreguntas" value="{{ count($cuestPreguntas) }}" />
                                  <input type="hidden" id="token" name="token" value="{{ csrf_token() }}" content="{{ csrf_token() }}" />
                                <div class="row">
                                    <?php $countPreg=1; ?>
                                    @foreach($cuestPreguntas as  $cuestPregunta )
                                    <div class="col-lg-12">
                                                <table>
                                                  <thead>
                                                    <tr>
                                                      <th ><b>{{ $cuestPregunta->pregunta   }}<b></th>
                                                    </tr>
                                                    <tr>
                                                      <th>&nbsp;</th>
                                                    </tr><br>
                                                  </thead>
                                                  <td>

                                                      @foreach($cuestRespuestas as  $cuestRespuesta )
                                                          @if($cuestPregunta->idPregunta  == $cuestRespuesta->idPregunta )
                                                          @if($cuestRespuesta->tipoCaja == '1' )
                                                               {!!Form::textarea('value',$cuestRespuesta->value,['id'=>'value_'.$cuestRespuesta->idCA.'',
                                                               'class'=>'form-control tama col-lg-12', 'rows' =>'1','cols'=>'100','placeholder'=>'Nombre de respuesta',
                                                               'onblur'=>'guardaRespuesta('.$cuestRespuesta->idCA.','.$cuestPregunta->idPregunta.','.$countPreg.')'])!!}
                                                               {!!Form::hidden('value',$cuestPregunta->idCuestion,['id'=>'idCuestion','class'=>'col-lg-12'])!!}
                                                               {!! Form::close() !!}
                                                           @endif
                                                           @if($cuestRespuesta->tipoCaja == '2' )
                                                             <a href='{{ route('file.index',['id'=>$cuestRespuesta->idCA,'name'=>$idCuestionario[0]->quname, 'folio' => $folio, 'secciones' => '0']) }}' class='btn btn-primary' title='Editar' $disabledButtom> <i class='fa fa-edit'></i></a>
                                                             {{ $cuestRespuesta->respuesta }}
                                                           @endif

                                                               @if($cuestRespuesta->tipoCaja == '3' )
                                                                      {!!Form::model($cuestRespuesta,['route'=>['miscuestionarios.update',$cuestRespuesta->idCA],'method'=>'PUT'])!!}
                                                                          {!! Form::select('value',[
                                                                              ''=>'N/A',
                                                                              '0'=>'0',
                                                                              '1'=>'1',
                                                                              '2'=>'2',
                                                                              '3'=>'3',
                                                                              '4'=>'4',
                                                                              '5'=>'5'
                                                                              ],null,['id'=>'value','class'=>'form-control'])
                                                                          !!}
                                                                          {{ $cuestRespuesta->respuesta }}
                                                                        {!! Form::close() !!}
                                                                        {{ Form::button('Guardar', ['type' => 'submit', 'class' => 'btn btn-success','title'=>'Inactivar']) }}
                                                                  @endif
                                                            @if($cuestRespuesta->tipoCaja == '4' )
                                                                     @if($cuestRespuesta->value !=  '')
                                                                       <input type="radio" name="radio_{{ $cuestPregunta->idPregunta }}" id="value_{{ $cuestRespuesta->idCA }}"
                                                                       onClick="guardaRespuestaRadio({{ $cuestRespuesta->idCA }},{{ $cuestRespuesta->valCheck }},{{ $cuestPregunta->idPregunta }}, {{ $cuestPregunta->idCuestion }},{{$countPreg}})"
                                                                       checked />
                                                                     @else
                                                                       <input type="radio" name="radio_{{ $cuestPregunta->idPregunta }}" id="value_{{ $cuestRespuesta->idCA }}"
                                                                       onClick="guardaRespuestaRadio({{ $cuestRespuesta->idCA }},{{ $cuestRespuesta->valCheck }},{{ $cuestPregunta->idPregunta }}, {{ $cuestPregunta->idCuestion }},{{$countPreg}} )" />
                                                                     @endif
                                                                     {{ $cuestRespuesta->respuesta  }}
                                                            @endif
                                                            @if($cuestRespuesta->tipoCaja == '6' )
                                                            <div  class="pre-scrollable">
                                                              <table class="table nueva table-bordered table-hover header-fixed"  id="sometable">
                                                                  <thead>
                                                                    <tr>
                                                                      <td >
                                                                        @if($cuestRespuesta->value !=  '')
                                                                            <input class=" " type="checkbox" name="check_{{ $cuestPregunta->idPregunta }}" id="value_{{ $cuestRespuesta->idCA }}"
                                                                            onClick="guardaRespuestaCheck({{ $cuestRespuesta->idCA }},{{ $cuestRespuesta->valCheck }},{{ $cuestPregunta->idPregunta }},{{ $cuestPregunta->idCuestion }},{{$countPreg}})"
                                                                            checked />
                                                                        @else
                                                                          <input class=" " type="checkbox" name="check_{{ $cuestPregunta->idPregunta }}" id="value_{{ $cuestRespuesta->idCA }}"
                                                                          onClick="guardaRespuestaCheck({{ $cuestRespuesta->idCA }},{{ $cuestRespuesta->valCheck }},{{ $cuestPregunta->idPregunta }},{{ $cuestPregunta->idCuestion }},{{$countPreg}})" />
                                                                      @endif
                                                                        {{ $cuestRespuesta->respuesta  }}

                                                                      </td>
                                                                    </tr>
                                                                   </thead>
                                                                   <tbody>
                                                                   </tbody>

                                                                 </div>
                                                             @endif
                                                       @endif
                                                      @endforeach
                                                    </td>
                                                </table>
<<<<<<< HEAD
                                      </div>
=======
	                                   </div>
>>>>>>> 8f4e320ea0510daec4932c459c7ba8e038e10003
                                     <?php $countPreg++; ?>
                                     @endforeach
                                  </div>

                                </div>
                                </div>
                          </div>
                    </section>
                  </div>
            </section>
      </section>
@stop