routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* vista de idiomas  */
    Route::group(['middleware' => ['web']], function () {
  	    Route::resource('/','AdminController');

		Route::group(['middleware' => ['web']], function () {
			Route::get('lang/{lang}', function ($lang) {
			     App::setLocale($lang);
			        session(['lang' => $lang]);
				          return \Redirect::back();
			             })->where([
				                 'lang' => 'en|es|fr|pt'
         ]);
        });
       });
    /* fin de ruta de idiomas  */
Auth::routes();
Route::get('/respuesta',function(){
  return view('response');
});
Route::get('activacion/{code}','UserController@activate');
Route::post('complete/{id}','UserController@complete');
// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('cities/{id}','Auth\RegisterController@getCities');
Route::get('lada/{id}','Auth\RegisterController@getlada');

Route::get('reactivacion',function(){
  return view('auth.reactivacion');
});
  /* vista de validador de correo si existe */
  Route::post('validacorreor','UserController@validar');
  /* fin de ruta de validaro de correo */

Route::group(['middleware'=>'auth'],function(){
          Route::get('/home', 'HomeController@index')->name('home');
          Route::resource('micuestionarios','DapauditorController');
          //  Cuestionarios asignados al cliente
          Route::resource('miscuestionarios','MisCuestionariosController');
          Route::get('subsecciones/{id}','MisCuestionariosController@getSubsection')->name('subsecciones.inicio');
          Route::get('preguntas/{seccion}/{subseccion}','MisCuestionariosController@getQuestions')->name('preguntas.inicio');

          // Administrador de Cuestionarios
          Route::get('respuesta/respuesta/{val1}','AnswerController@respuesta');
          Route::resource('respuesta','AnswerController');
          Route::resource('pregunta','QuestionController');
          Route::resource('cuestionario','QuestionnaireController');
          Route::get('cuestionariostatus/{st}','QuestionnaireController@muestraActivInac');
          Route::resource('asingapregunta','QuestionnaireAnswerController');
          Route::get('tipocuest/{id}','QuestionnaireAnswerController@getCuestionarios');
          Route::resource('tipocuestionario','QuestionnaireTypeController');
          Route::resource('configcuestionario','QuestionnaireConfigurationController');
          Route::get('respuestaselect','AnswerController@getAnswer');
          Route::get('preguntaselect','QuestionController@getQuestion');
          Route::post('savetemplate','FilesController@guardaTemplate'); // Ruta para guardar los templates(Archivos) para cada respuesta
          Route::resource('file','FilesController');
          Route::resource('fileTemplate','FileTemplateController'); // Ruta que envia a la pestaña para cargar los templates por pregunta/respuesta(Archivos)
          Route::resource('tempcuest','FileTemplateCuestionarioController'); // Ruta que envia a la pestaña para cargar los templates por cuestionario(Archivos)
          Route::resource('filecuest','FilesQuestionarieController'); // Ruta que envia a la pestaña para cargar los templates por pregunta/respuesta(Archivos)
          Route::get('download/{file}','FilesController@download');
          Route::get('downloadCuest/{file}','FilesQuestionarieController@download');
          Route::get('downloadTemplate/{file}','FileTemplateController@download');
          Route::get('downloadTemplateCues/{file}','FilesQuestionarieController@download');
          Route::get('signiv1/{id}','FilesController@signiv1'); // Enviar al siguiente nivel os archivos al perfil auditor desde el perfil usuario
          Route::get('signiv1Cuest/{id}','FilesQuestionarieController@signiv1'); // Enviar al siguiente nivel os archivos al perfil auditor desde el perfil usuario
          Route::get('signiv1Temp/{id}','FileTemplateController@signiv1');

          Route::resource('catalogo','CatalogoController');
          // Administrador alta de tipo de giro
<<<<<<< HEAD
 
=======

>>>>>>> 8f4e320ea0510daec4932c459c7ba8e038e10003
          Route::resource('giro','GiroController');
          Route::resource('empresa','EmpresaController');
          Route::resource('planes','PlanesController');
          Route::resource('dap','DapController');
          Route::resource('pais','PaisController');
          Route::resource('ciudad','CiudadController');
          Route::resource('agrega','Contri_citiController');
          Route::resource('tipoArchivo','TipoArchivoController');
          Route::resource('calificacionArchivo','CalificacionArchivoController');


      Route::resource('user','UserController');

      Route::middleware('role:Admin')->put('user/{user}/roles','UsersRolesController@update')->name('user.roles.update');

      Route::middleware('role:Admin')->put('user/{user}/permissions','UsersPermissionsController@update')->name('user.permissions.update');

      Route::resource('roles','RoleController');

      Route::resource('permissions','PermissionsController');

      /* ruta para ver el email la vista */
      Route::get('email', function(){
        return new App\Mail\LoginCredentials(App\User::first(),'123456');
      });
      Route::resource('auditFile','AuditoriaArchivosController');
      Route::resource('analisis','AnalisController');
      Route::get('valor/{id}','AnalisController@Valorcatalogo');
      Route::get('grado/{id}','AnalisController@GradoRiesgo');
      Route::get('val/{id}','AriesgoController@Valorcatalogo');
      Route::get('grad/{id}','AriesgoController@GradoRiesgo');
      Route::resource('ariesgo','AriesgoController');
      Route::resource('ariesgoEjec','AriesgoEjecutivoController');
      Route::resource('operacion','catalog_masterController');
      Route::resource('actividad','ActividadController');
      Route::resource('descripcion','DescripcionController');
      Route::resource('catalogos','CataAnalisisController');

      Route::get('descargar-productos', 'GiroController@pdf')->name('products.pdf');
      Route::get('descargar-producto', 'GiroController@excel')->name('products.excel');
      // Route::get('pdf', 'PdfController@invoice');
      Route::get('analisis', 'AriesgoController@pdf')->name('alanisis.pdf');
      Route::get('analisisEjec', 'AriesgoEjecutivoController@pdf')->name('analisisEjec.pdf');
      Route::get('analisisEjecGr', 'AriesgoEjecutivoController@muestraContenido')->name('analisisEjecGr.muestraContenido'); // Ruta para guardar la imagen generada de la grfica
      Route::resource('divisas', 'DivisasController');
      Route::resource('cotizador', 'CotizadorController');
      Route::get('div/{id}','CotizadorController@getid');
      Route::resource('cotizaciones', 'CotizadorUser');
      Route::get('pdfcotizacion', 'CotizadorUser@pdf')->name('pdfcotizacion.pdf');
      Route::resource('admincotizador', 'AdminCotizadorController');

});

Route::resource('prueba','DapController');

resources/views/analisis/operacion/edit.blade.php
<!-- Modal -->
<div class="modal fade" id="editOperacion" role="dialog" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <!-- Modal content-->
    <div class="modal-content bgColorWhite">
      <div class="modal-header modalcolor">
        <h4 class="letracolor">Editar Operación</h4>
        <button type="button" class="close blanco" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
            <!-- Mensajes exitosos -->
            <div id="msj-success" class="alert alert-success" role="alert" style="display:none">
                Operación actializado correctamente
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <input type="hidden" id="token" name="token" value="{{ csrf_token() }}" />
            <input type="hidden" id="cmfkEd" />
            {!! Form::label('cmdescEd','Nombre') !!}
            {!! Form ::text('cmdescEd', null, ['id'=> 'cmdescEd','class'=>'form-control'])!!}
            <div id="msj-errorEd" class="alert-danger" role="alert" style="display:none">
                <strong class="help-block blanco" id="msjEd"></strong>
            </div>
            <div class="modal-footer">
              <input type="button" class="btn btn-primary" id="EditOperacion" value="Actualizar" />
            </div>
      </div>
    </div>
  </div>
</div>

resources/views/analisis/operacion/index.blade.php
@extends('layouts.adm')
	@section('content')
			@include('analisis.operacion.modal')
			@include('analisis.operacion.edit')

			<div class="inner-wrapper">
				<section role="main" class="content-body pb-0">
					<!-- <header class="page-header">
						<h2>Giros</h2>

						<div class="right-wrapper text-right">
							<ol class="breadcrumbs">
								<li>
									<a href="{{url("home")}}">
										<i class="fa fa-home"></i>
									</a>
								</li>
								<li><span class="blanco"></span></li>
							</ol>

						</div>
					</header> -->
					@include('flash::message')
					@if(Session::has('message'))
							<div class="alert alert-success" role="alert">
								{{Session::get('message')}}
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
					@endif
					@if(Session::has('flash_delete'))
							<div class="alert alert-warning " role="alert">
								{{Session::get('flash_delete')}}
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
					@endif
					<br>
					@include('flash::message')
					@if(Session::has('flash_success'))
							<div class="alert alert-success" role="alert">
								{{Session::get('flash_success')}}
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
					@endif
					<div class="col-md-12">
								<section class="card card-featured card-featured-primary mb-4">
									<header class="card-header">
										<div class="card-actions">
                      <a href="{{ url('tipocuestionario' )}}" >
                        <button type="button"class="btn btn-outline btn-link"style="color:#fff;">	<i class="fa fa-undo">	Regresar</i></button>
                      </a>

												<button type="button" class="btn btn-outline btn-link" data-toggle='modal'
												data-target='#agregaroperacion' style="color:#fff;" data-id='{{ $cuestionarios[0]->ctfk }}'>	<i class="fa fa-plus"> 	Agregar</i></button>
													<!-- <button type="button" class="btn btn-outline btn-link" data-toggle='modal'
													data-target='#descargargiro' style="color:#fff;">	<i class="fa fa-plus"> 	Descargar layaout</i></button> -->

										</div>

										<h2 class="card-title blanco">Analisis de Riesgo ({{$cuestionarios[0]->ctname}})</h2>
											<input type="hidden" name="status" id="status" value="{{  $status }}" />
									</header>
									<div class="card-body">
										<!-- <code>.card-featured.card-featured-primary</code> -->
										<div class="	">
											  <h4 class="text-center">Estándar</h4>
											<!-- <div class="container">
											<form style="border: 4px solid #a1a1a1;margin-top: 15px;padding: 10px;" action="{{ URL::to('importExcel') }}" class="form-horizontal" method="post" enctype="multipart/form-data">
												<input type="file" name="import_file" />
												<button class="btn btn-primary">Import File</button>
											</form>
										</div> -->
											<div class="tabs tabs-primary">
												<ul class="nav nav-tabs">
													<li class="nav-item active">
														<a class="nav-link active" href="#altas" data-toggle="tab"><i class="fa fa-star"></i> Altas</a>
													</li>
													<li class="nav-item">
														<a class="nav-link" href="#bajas" data-toggle="tab">Bajas</a>
													</li>
												</ul>
												<div class="tab-content">
													<div  id="altas" class="tab-pane active">
														<table width="100%" class="table table-responsive-md table-sm  ">
															<thead>
																	<tr>
																		<td><b>ID</b></td>
																		<td><b>IdCatálogo</b></td>
																		<td><b>Operación</b></td>
																		<td align="center"><b>Estatus</b></td>
																		<td><b>Acción</b></td>
																	</tr>
															</thead>
															@foreach($operacion as $opera)
																<tbody>
																		<tr class="odd gradeX">
																				<td>{{$opera->cmfk }}</td>
																				<td>{{$opera->cmtpcat }}</td>
																				<td>{{ $opera->cmdesc }}</td>
																				<td align="center">
																					Alta
																				</td>
																				<td class="">
																						<div class="row">
																								<div class="col-md- col-md-offset-1">
																									{!!Form::open(['route'=> ['operacion.destroy',$opera->cmfk, 'estatus' => $opera->cmstatus, 'desc' => $opera->cmdesc],'method'=>'DELETE'])!!}
																										{{ Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-xs btn-default','title'=>'Inactivar']) }}
																										{!!Form::close()!!}
																								</div>
																								<div class="col-md-1 col-md-offset-1">
																									<a data-toggle='modal' id="editOperacion" data-target='#editOperacion'
																									 data-id='{{ $opera->cmfk }}' class="btn btn-xs btn-default ">  <i class="fa fa-edit"></i></a>
																								</div>
																								<div class="col-md-1 col-md-offset-1">
				                                          <a  href="{{ route('actividad.index',['id' => $opera->cmfk, 'id2'=>$cuestionarios[0]->ctfk] )}}" class="btn btn-xs btn-default "> <i class="fa fa-plus"> Sub estándar</i></a>
				                                        </div>
																					</div>
																				</td>
																		</tr>
																	</tbody>
																@endforeach
														</table>
														<div class=" pull-right">
																{{ $operacion->appends(['status' => 1,'id' => $tipoCuestionario])}}
														</div>
													</div>
													<div id="bajas" class="tab-pane fade">
														<table width="100%" class="table table-responsive-md table-sm 	">
															<thead>
																	<tr>
																		<td><b>ID</b></td>
																		<td><b>IdCatálogo</b> </td>
																		<td><b>Operación</b></td>
																		<td align="center"><b>Estatus</b></td>
																		<td><b>Acción</b></td>
																	</tr>
															</thead>
																@foreach($operacionbaja as $operabaja)
																<tbody>
																		<tr class="odd gradeX">
                                      <td>{{$operabaja->cmfk }}</td>
																			<td>{{$operabaja->cmtpcat }}</td>
                                      <td>{{ $operabaja->cmdesc }}</td>
																				<td align="center">
																					Inactivo
																				</td>
																				<td>
																						<div class="row">

																								<div class="col-md- col-md-offset-">
																									{!!Form::open(['route'=> ['operacion.destroy',$operabaja->cmfk, 'estatus' => $operabaja->cmstatus, 'desc' => $operabaja->cmdesc],'method'=>'DELETE'])!!}
																										{{ Form::button('<i class="fa fa-check"></i>', ['type' => 'submit', 'class' => 'btn btn-xs btn-default','title'=>'Inactivar']) }}
																										{!!Form::close()!!}
																								</div>
																								<div class="col-md-1 col-md-offset-1">
																									<a data-toggle='modal' id="editGiro" data-target='#editGiro'
																							 data-id='{{ $operabaja->cmfk }}' class="btn btn-xs btn-default ">  <i class="fa fa-edit"></i></a>
																							</div>
																							<div class="col-md-1 col-md-offset-1">
																								<a  href="{{ route('actividad.index',['id' => $operabaja->cmfk, 'id2'=>$cuestionarios[0]->ctfk] )}}" class="btn btn-xs btn-default "> <i class="fa fa-plus"> Actividad</i></a>
																						  </div>
																					</div>
																				</td>
																		</tr>
																	</tbody>
																@endforeach
														</table>
														<div class=" pull-right">
																{{ $operacionbaja->appends(['status' => 0,'id' => $tipoCuestionario])}}
														</div>
												</div>
											</div>
											</div>

									</div>
								</section>
							</div>



					<!-- end: page -->
				</section>
			</div>

			@stop
@section('scripts')
	{!!Html::script('js/Generics.js')!!}
	{!!Html::script('js/admin/createoperacion.js')!!}
	{!!Html::script('js/admin/operacion.js')!!}
@endsection

resources/views/analisis/operacion/modal.blade.php
<!-- Modal -->
<div class="modal fade" id="agregaroperacion" role="dialog" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content bgColorWhite">
      <div class="modal-header modalcolor">
        <h4 class="letracolor">Agregar Operación</h4>
        <button type="button" class="close blanco" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
            <input type="hidden" id="token" name="token" value="{{ csrf_token() }}" />
            <div class="form-group">
              <!-- Mensajes exitosos -->
              <div id="msj-success" class="alert alert-success" role="alert" style="display:none">
                  Operación agregada correctamente
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <input type="hidden" id="qtfk" value="{{$cuestionarios[0]->ctfk}}" />
              {!! Form::label('cmdescCre','Nombre') !!}
              {!! Form ::text('cmdescCre',null, ['class'=>'form-control','id'=>'cmdescCre','placeholder'=>'Nombre del la Operación'])!!}
              <div id="msj-errorCre" class=" alert-danger" role="alert" style="display:none">
                  <strong class="help-block blanco" id="msjCre"></strong>
              </div>

            </div>
      </div>
      <div class="modal-footer">
        <input type="button" class="btn btn-outline btn-success" id="btnCreateOperacion" value="Guardar" />
      </div>
    </div>

  </div>
</div>

<!-- Large modal -->